### ISSUE TITLE
helper named 'ember-ic-you' could not be found

### ISSUE THREAD

**Issue by TiSer** [Vestorly/ember-cli-infinite-scroll#12]
After adding "infinite-scroll" as component I have an error at browser's console:
`Assertion Failed: A helper named 'ember-ic-you' could not be found`

**Comment by JeffLuong** [comment]
@TiSer can you provide us more context? What does your template look like? Also can you confirm that you have `ember-ic-you` installed?

**Comment by TiSer** [comment]
@JeffLuong No, I didn't install it, since there are no such information at "ember-cli-infinite-scroll" wiki.

**Comment by JeffLuong** [comment]
@TiSer ah ok, we'll make sure to add it in the wiki. Does error still occurs after installing it?
