### ISSUE TITLE
Ember 1.13 flags install as `The `ember generate` command requires an entity name to be specified`

### ISSUE THREAD

**Issue by timkellogg** [Vestorly/ember-cli-infinite-scroll#6]
In my ember-cli 1.13.8 application I tried to install using `ember install ember-cli-infinite-scroll` and the install errors out with `The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.`

Is this a version problem or is there something I'm missing?
Thanks

**Comment by jondayton** [comment]
I'll take a look at it.

**Comment by jondayton** [comment]
@timkellogg it looks like it was a conflict with the way the default templates were being generated as previous versions of this addon were made using an older version of ember-cli. I pushed a fix and tried it with a 1.13.x app, it's published to npm as version 0.3.3. let me know if you have any more issues.

**Comment by timkellogg** [comment]
The installing went through - thanks.
